media:
  input: public
  output: /
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/posts
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: author, label: Author, type: string }
      - { name: title, label: Title, type: string, required: true }
      - { name: ogImage, label: Title, type: string }
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: description, label: Description, type: string }
      - { name: body, label: Body, type: rich-text }
  - name: about
    label: About page
    type: file
    path: src/content/about/index.md
    fields:
      - { name: title, label: Title, type: string }
      - { name: meta_title, label: Meta Title, type: string }
      - { name: description, label: Description, type: string }      
      - { name: image, label: Image, type: string, default: images/author.png }
      - { name: draft, label: Draft, type: boolean }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }